ALTER SESSION SET current_schema=ORDSYS;

DROP TABLE LOAI_HANG ;

CREATE TABLE LOAI_HANG
( ID NUMBER PRIMARY KEY ,
  MA_LOAI_HANG VARCHAR2(100) ,
  TEN_LOAI_HANG VARCHAR2(200),
  NGUOI_TAO VARCHAR2(100),
  THOIGIAN_TAO DATE DEFAULT sysdate ,
  NGUOI_SUA VARCHAR2(100),
  THOIGIAN_SUA DATE
);

CREATE TABLE XUAT_XU
(
 ID NUMBER PRIMARY KEY ,
 MA_XUAT_XU VARCHAR2(100) ,
 TEN_XUAT_XU VARCHAR2(100) ,
 NGUOI_TAO VARCHAR2(100),
 THOIGIAN_TAO DATE DEFAULT sysdate ,
 NGUOI_SUA VARCHAR2(100),
 THOIGIAN_SUA DATE
 );
 
DROP_TABLE DON_VI_TINH ;
 CREATE TABLE DON_VI_TINH
(
 ID NUMBER PRIMARY KEY ,
 MA_DON_VI_TINH VARCHAR2(100) ,
 TEN_DON_VI_TINH VARCHAR2(100) ,
 NGUOI_TAO VARCHAR2(100),
 THOIGIAN_TAO DATE DEFAULT sysdate ,
 NGUOI_SUA VARCHAR2(100),
 THOIGIAN_SUA DATE
 );
 DROP TABLE QUI_CACH ;
 CREATE TABLE QUI_CACH
(
 ID NUMBER PRIMARY KEY ,
 MA_QUI_CACH VARCHAR2(100) ,
 TEN_QUI_CACH VARCHAR2(100) ,
 NGUOI_TAO VARCHAR2(100),
 THOIGIAN_TAO DATE DEFAULT sysdate ,
 NGUOI_SUA VARCHAR2(100),
 THOIGIAN_SUA DATE
 );
DROP TABLE HANG_HOA ;

CREATE TABLE HANG_HOA 
( ID NUMBER  PRIMARY KEY , 
  MA_HANG VARCHAR2(500) ,
  TEN_HANG VARCHAR2(500) ,
  LOAI_HANG_ID NUMBER, 
  XUAT_XU_ID  NUMBER ,
  DON_VI_TINH_ID NUMBER,
  QUI_CACH_ID NUMBER,
  DON_GIA NUMBER ,
  GIA_BAN NUMBER ,
  GHI_CHU VARCHAR2(1000) ,
  NGUOI_TAO VARCHAR2(100),
  THOIGIAN_TAO DATE,
  NGUOI_SUA VARCHAR2(100),
  THOIGIAN_SUA DATE
)
;

ALTER TABLE HANG_HOA
ADD CONSTRAINT FK_HANG_HOA_LOAI_HANG
  FOREIGN KEY (LOAI_HANG_ID)
  REFERENCES LOAI_HANG(ID);
  

ALTER TABLE HANG_HOA
ADD CONSTRAINT FK_HANG_HOA_XUAT_XU
  FOREIGN KEY (XUAT_XU_ID)
  REFERENCES XUAT_XU(ID);
  
ALTER TABLE HANG_HOA
ADD CONSTRAINT FK_HANG_HOA_DON_VI_TINH
  FOREIGN KEY (DON_VI_TINH_ID)
  REFERENCES DON_VI_TINH(ID);

  ALTER TABLE HANG_HOA
ADD CONSTRAINT FK_HANG_HOA_QUI_CACH
  FOREIGN KEY (QUI_CACH_ID)
  REFERENCES QUI_CACH(ID);

 