package model;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jan 15 11:37:54 PST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ViewTonKhoHangHoaImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ViewTonKhoHangHoaImpl() {
    }
}

